<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <AssemblyName>BTCPayServer.Plugins.Stash</AssemblyName>
    <RootNamespace>BTCPayServer.Plugins.Stash</RootNamespace>
  </PropertyGroup>
  <!-- -->
  <!-- Plugin specific properties -->
  <PropertyGroup>
    <Product>Stash</Product>
    <Description>Automated treasury management plugin for BTCPay Server. Virtually segregate a percentage of incoming payments for tax liability hedging or cold storage accumulation, with batch withdrawal execution when thresholds are met.</Description>
    <Version>0.0.1</Version>
  </PropertyGroup>
  <!-- Plugin development properties -->
  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <PreserveCompilationContext>false</PreserveCompilationContext>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <!-- This will make sure that referencing BTCPayServer doesn't put any artifact in the published directory -->
  <ItemDefinitionGroup>
    <ProjectReference>
      <Properties>StaticWebAssetsEnabled=false</Properties>
      <Private>false</Private>
      <ExcludeAssets>runtime;native;build;buildTransitive;contentFiles</ExcludeAssets>
    </ProjectReference>
  </ItemDefinitionGroup>

  <ItemGroup Condition="'$(Configuration)' != 'Release'">
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.10.0"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.10.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\submodules\btcpayserver\BTCPayServer\BTCPayServer.csproj" ExcludeAssets="runtime">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>

